#define pi 3.14156
int int_max(int x, int y);
int int_min(int x, int y);
double double_max(double x, double y);
double double_min(double x, double y);
double square(double x);
double sqr(double x);
double Z(double x);
double P(double x);
double Q(double x);
double I(double x, double a, double b);
double A(double t, int nu);
double t_prob(double t, int nu);
double Gamma(int n);
double logGamma(int n);
double log_factorial(int n);
double log_poiss_pr(int x, double lambda);
double poiss_pr(int x, double lambda);
double poiss_p_value(int x, double lambda);
double log_n_choose_k(int n, int k);
double right_bin_p_value(int x, double p, int n);
double left_bin_p_value(int x, double p, int n);
int right_int(double x);
double double_mmax(double x, double y);
double int_pow(double x, int p);
double poiss_pr(double zeta, int k);
double log_poiss_pr(double zeta, int k);
double log_binomial_pr(int x, int n, double p);
double binomial_pr(int x, int n, double p);
double BesselI(int n, double z);
double _BesselK0(double x);
double BesselK0(double x);
double BesselK1(double x);
double BesselK(int n, double z);
double BesselK_semi_int(double nu, double z);
double logBesselK_semi_int(double nu, double z);
double average(const vector<double>& v);
double B0(double x);
double B1(double x);
double BK(int n, double z);
double new_BesselK(int n, double z);
double logBesselK(int n, double z);
double norm_dens(double x, double mu, double sigma);
double log_norm_dens(double x, double mu, double sigma);
double gamma_dens(double x, double beta, int k);
double log_exp_dens(double x, double lambda);
